### ISSUE TITLE
Pasar un String como parámetro

### ISSUE THREAD

**Issue by sdsoldi** [Heavyblade/cirrus#17]
Buenos días,

Estoy intentando pasar un parámetro numérico como String y estoy teniendo problemas.

Estoy pasando un parámetro 01 y 0101. Cuando la longitud es de 4 o más caracteres me devuelve String "0101" pero cuando intento pasar una cadena de 3 o menos caracteres lo convierte a numérico.

Si pongo return params.body.seccion:

Ejemplos:
01 -> "1"
010 -> "10"
000 -> ""
0000 -> "0000"
0101 -> "0101"

Y lo que me gustaría que devolviese params.body.seccion:
01 -> "01"
010 -> "010"
000 -> "000"

Existe alguna forma de poder obtener el string?

**Comment by Heavyblade** [comment]
Hola,

SI, hay un problema ahi al ser todos caracteres numéricos Cirrus tratará de definir el tipo, de momento la solución más aplicable seria enviar esos valores entre comillas simples y quitárselas antes de guardarlos o procesarlos.
